In [1]:
def remove_dublicates(a):
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i]==a[j] and i!=j:
                print((i+1)*j)
                a[j] = 0
    b = []
    for i in range(len(a)):
        if a[i]!=0:
            b.append(a[i])

    return b

In [2]:
import pandas as pd

C:\Users\Lenovo\miniconda3\envs\tfgpu\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Lenovo\miniconda3\envs\tfgpu\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\Lenovo\miniconda3\envs\tfgpu\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
f = open("IITB.en-hi.en","r",encoding='utf-8')
lines = f.readlines()
data = []

for line in lines:
    data.append(line)
    
print(len(data))

1659083


In [4]:
df_english = pd.DataFrame(data,columns=['sentences'])

In [5]:
len(df_english)

1659083

In [6]:
df_english.head()

sentences
0  Give your application an accessibility workout\n
1               Accerciser Accessibility Explorer\n
2  The default plugin layout for the bottom panel\n
3     The default plugin layout for the top panel\n
4  A list of plugins that are disabled by default\n

In [7]:
df_english['sentences'] = df_english['sentences'].apply(lambda x: x[:-1])

In [8]:
df_english

sentences
0           Give your application an accessibility workout
1                        Accerciser Accessibility Explorer
2           The default plugin layout for the bottom panel
3              The default plugin layout for the top panel
4           A list of plugins that are disabled by default
...                                                    ...
1659078  The Prime Minister, Shri Narendra Modi has con...
1659079  In a tweet, the Prime Minister said, congratul...
1659080  I also congratulate all those who took oath as...
1659081  The NDA family will work together for the prog...
1659082  I assure all possible support from the Centre ...

[1659083 rows x 1 columns]

In [9]:
df_english['flag'] = df_english['sentences'].apply(lambda x: 'True' if type(x)==type(df_english['sentences'][0]) and len(x)>30 and len(x)<90 else 'False')
flag = df_english['flag']
df_english.head(12)

sentences   flag
0      Give your application an accessibility workout   True
1                   Accerciser Accessibility Explorer   True
2      The default plugin layout for the bottom panel   True
3         The default plugin layout for the top panel   True
4      A list of plugins that are disabled by default   True
5                                  Highlight duration  False
6   The duration of the highlight box when selecti...   True
7                              Highlight border color  False
8      The color and opacity of the highlight border.   True
9                                Highlight fill color  False
10       The color and opacity of the highlight fill.   True
11                                        API Browser  False

In [10]:
f = open("IITB.en-hi.hi","r",encoding='utf-8')
lines = f.readlines()
data = []
string = '' 
for line in lines:
    data.append(line[:-1])

In [11]:
data = list(zip(data, flag))
df_hindi = pd.DataFrame(data,columns=['sentences','flag'])

In [12]:
error = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
         'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '(', ')' ]
special_char=['/','.','¨','¾','®','¥','à','¤','©','+','=','%','@','#','$','`','~','-','1','2','3','4','5','6','7','8','9','0']

error=error+special_char

string = df_hindi['sentences'][45534]
string1 ='दायाँ स्थिति इंच अक्षर'
string2 = 'GL पिक्सेल उद्धरण ऑब्जेक्ट के प्रयोग को अक्षम करें'
def check1(x):
    for k in error:
        try: 
            x.index(k.upper())
            return False
        except ValueError as v:
            pass
        
    return True

def check2(x):
    for k in error:
        try: 
            x.index(k.lower())
            return False
        except ValueError as v:
            pass
        
    return True

print(string)
print(not check1(string) or not check2(string))
print(not check1(string1) or not check2(string1))
print(not check1(string2) or not check2(string2))
df_hindi['flag1'] = df_hindi['sentences'].apply(lambda x: 'False' if (not check1(x)  or not check2(x)) else 'True')

GL पिक्सेल उद्धरण ऑब्जेक्ट के प्रयोग को अक्षम करें
True
False
True


In [13]:
df_hindi['flag2'] = df_hindi['sentences'].apply(lambda x: 'True' if len(x)<90 else 'False')

In [14]:
flag1 = df_hindi['flag1']
flag2 = df_hindi['flag2']
df_hindi = df_hindi[df_hindi['flag'] == 'True']
df_hindi = df_hindi[df_hindi['flag1'] == 'True']
df_hindi = df_hindi[df_hindi['flag2'] == 'True']
df_hindi = pd.DataFrame(df_hindi['sentences'][:100000])
df_hindi = df_hindi.reset_index(drop = True)



df_english['flag1'] = flag1
df_english['flag2'] = flag2
df_english = df_english[df_english['flag'] == 'True']
df_english = df_english[df_english['flag1'] == 'True']
df_english = df_english[df_english['flag2'] == 'True']
df_english = pd.DataFrame(df_english['sentences'][:100000])
df_english = df_english.reset_index(drop=True)

In [15]:
print(df_hindi.head(1))
print(df_english.head(1))

                                         sentences
0  अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें
                                        sentences
0  Give your application an accessibility workout


In [16]:
print(len(df_hindi), len(df_english))

100000 100000


In [17]:
Hindi = [f'[start] {sentence} [end]' for sentence in df_hindi['sentences']] 
English = [sentence for sentence in df_english['sentences']]

In [18]:
text_pairs = []

for i in range(len(Hindi)):
    text_pairs.append([English[i], Hindi[i]])

In [19]:
import random
for i in range(3):
    print(random.choice(text_pairs))

['Bhagat Singh established the Youth India Assembly for the freedom of India.', '[start] भगत सिंह ने भारत की आज़ादी के लिए नौजवान भारत सभा की स्थापना की थी।  [end]']
["Here 's the balloon being filled up with helium,", '[start] यहां गुब्बारे मे हीलियम भरा जा रहा है,  [end]']
['So remind. You are only a reminder.', '[start] अच्छा तो नसीहत करो! तुम तो बस एक नसीहत करनेवाले हो [end]']


In [20]:
max1 = 0
max2 = 0
index1 = 0
index2 = 0
for i in range(len(text_pairs)):
    if len(text_pairs[i][1])>max2:
        max2 = len(Hindi[i])
        index2 = i
    if len(text_pairs[i][0])>max1:
        max1 = len(English[i])
        index1 = i
        
print(index1, index2)

14562 14793


In [21]:
random.shuffle(text_pairs)
length = len(text_pairs)
len_val_samples = int(0.15 * length)

In [22]:
len_train_samples = length - 2*len_val_samples

train_pairs = text_pairs[:len_train_samples]
val_pairs = text_pairs[len_train_samples:len_train_samples+len_val_samples]
test_pairs = text_pairs[len_train_samples+len_val_samples:]

In [23]:
import tensorflow as tf
import tensorflow.keras.layers as layers
import tensorflow.keras as keras
import re
import string

strip_chars = string.punctuation
strip_chars = strip_chars.replace('[', '')
strip_chars = strip_chars.replace(']', '')

In [24]:
def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(
        lowercase, f"[{re.escape(strip_chars)}]", "")

vocab_size = 15000
sequence_length = 20

source_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length,
    
)
target_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length + 1,
    standardize=custom_standardization,
)
train_english_texts = [pair[0] for pair in train_pairs]
train_hindi_texts = [pair[1] for pair in train_pairs]
source_vectorization.adapt(train_english_texts)
target_vectorization.adapt(train_hindi_texts)

In [25]:
print(tf.__version__)

2.10.0


In [26]:
batch_size = 64

def format_dataset(eng, hin):
    eng = source_vectorization(eng)
    hin = target_vectorization(hin)
    return ({
        "english": eng,
        "hindi": hin[:, :-1],
    }, hin[:, 1:])

def make_dataset(pairs):
    eng_texts, hin_texts = zip(*pairs)
    eng_texts = list(eng_texts)
    hin_texts = list(hin_texts)
    dataset = tf.data.Dataset.from_tensor_slices((eng_texts, hin_texts))
    dataset = dataset.batch(batch_size)
    dataset = dataset.map(format_dataset, num_parallel_calls=4)
    return dataset.shuffle(2048).prefetch(16).cache()

train_ds = make_dataset(train_pairs)
val_ds = make_dataset(val_pairs)

In [28]:
for inputs, targets in train_ds.take(1):
    print(f"inputs['english'].shape: {inputs['english'].shape}")
    print(f"inputs['hindi'].shape: {inputs['hindi'].shape}")
    print(f"targets.shape: {targets.shape}")
    print(inputs["hindi"])
    print(targets)

inputs['english'].shape: (64, 20)
inputs['hindi'].shape: (64, 20)
targets.shape: (64, 20)
tf.Tensor(
[[   2 1131 1139 ...    0    0    0]
 [   2  366 4302 ...    0    0    0]
 [   2   21  124 ...    0    0    0]
 ...
 [   2 2074   93 ...    0    0    0]
 [   2 1330    9 ...   12 1912    3]
 [   2 2203  481 ...    3    0    0]], shape=(64, 20), dtype=int64)
tf.Tensor(
[[1131 1139  699 ...    0    0    0]
 [ 366 4302 1036 ...    0    0    0]
 [  21  124   16 ...    0    0    0]
 ...
 [2074   93 9127 ...    0    0    0]
 [1330    9   33 ... 1912    3    0]
 [2203  481   10 ...    0    0    0]], shape=(64, 20), dtype=int64)


In [29]:
class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    def call(self, inputs, mask=None):
        if mask is not None:
            mask = mask[:, tf.newaxis, :]
        attention_output = self.attention(
            inputs, inputs, attention_mask=mask)
        proj_input = self.layernorm_1(inputs + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

In [30]:
class TransformerDecoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention_1 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.attention_2 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()
        self.layernorm_3 = layers.LayerNormalization()
        self.supports_masking = True

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

    def get_causal_attention_mask(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size, sequence_length = input_shape[0], input_shape[1]
        i = tf.range(sequence_length)[:, tf.newaxis]
        j = tf.range(sequence_length)
        mask = tf.cast(i >= j, dtype="int32")
        mask = tf.reshape(mask, (1, input_shape[1], input_shape[1]))
        mult = tf.concat(
            [tf.expand_dims(batch_size, -1),
             tf.constant([1, 1], dtype=tf.int32)], axis=0)
        return tf.tile(mask, mult)

    def call(self, inputs, encoder_outputs, mask=None):
        causal_mask = self.get_causal_attention_mask(inputs)
        if mask is not None:
            padding_mask = tf.cast(
                mask[:, tf.newaxis, :], dtype="int32")
            padding_mask = tf.minimum(padding_mask, causal_mask)
        attention_output_1 = self.attention_1(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=causal_mask)
        attention_output_1 = self.layernorm_1(inputs + attention_output_1)
        attention_output_2 = self.attention_2(
            query=attention_output_1,
            value=encoder_outputs,
            key=encoder_outputs,
            attention_mask=padding_mask,
        )
        attention_output_2 = self.layernorm_2(
            attention_output_1 + attention_output_2)
        proj_output = self.dense_proj(attention_output_2)
        return self.layernorm_3(attention_output_2 + proj_output)

In [31]:
class PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.token_embeddings = layers.Embedding(
            input_dim=input_dim, output_dim=output_dim)
        self.position_embeddings = layers.Embedding(
            input_dim=sequence_length, output_dim=output_dim)
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    def call(self, inputs):
        length = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_tokens = self.token_embeddings(inputs)
        embedded_positions = self.position_embeddings(positions)
        return embedded_tokens + embedded_positions

    def compute_mask(self, inputs, mask=None):
        return tf.math.not_equal(inputs, 0)

    def get_config(self):
        config = super(PositionalEmbedding, self).get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

In [33]:
embed_dim = 256
dense_dim = 2048
num_heads = 8

encoder_inputs = keras.Input(shape=(None,), dtype="int64", name="english")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(encoder_inputs)
encoder_outputs = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)

decoder_inputs = keras.Input(shape=(None,), dtype="int64", name="hindi")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(decoder_inputs)
x = TransformerDecoder(embed_dim, dense_dim, num_heads)(x, encoder_outputs)
x = layers.Dropout(0.5)(x)
decoder_outputs = layers.Dense(vocab_size, activation="softmax")(x)
transformer = keras.Model([encoder_inputs, decoder_inputs], decoder_outputs)

In [34]:
transformer.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 english (InputLayer)           [(None, None)]       0           []                               
                                                                                                  
 hindi (InputLayer)             [(None, None)]       0           []                               
                                                                                                  
 positional_embedding_2 (Positi  (None, None, 256)   3845120     ['english[0][0]']                
 onalEmbedding)                                                                                   
                                                                                                  
 positional_embedding_3 (Positi  (None, None, 256)   3845120     ['hindi[0][0]']            

In [35]:
transformer.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])
transformer.fit(train_ds, epochs=10, validation_data=val_ds)

Epoch 1/10
1094/1094 [==============================] - 82s 69ms/step - loss: 2.5244 - accuracy: 0.3439 - val_loss: 1.7395 - val_accuracy: 0.4774
Epoch 2/10
1094/1094 [==============================] - 77s 70ms/step - loss: 1.5795 - accuracy: 0.5302 - val_loss: 1.2865 - val_accuracy: 0.6067
Epoch 3/10
1094/1094 [==============================] - 80s 73ms/step - loss: 1.1902 - accuracy: 0.6276 - val_loss: 1.1362 - val_accuracy: 0.6538
Epoch 4/10
1094/1094 [==============================] - 81s 74ms/step - loss: 0.9908 - accuracy: 0.6788 - val_loss: 1.0818 - val_accuracy: 0.6762
Epoch 5/10
1094/1094 [==============================] - 81s 74ms/step - loss: 0.8635 - accuracy: 0.7111 - val_loss: 1.0585 - val_accuracy: 0.6889
Epoch 6/10
1094/1094 [==============================] - 82s 75ms/step - loss: 0.7727 - accuracy: 0.7344 - val_loss: 1.0533 - val_accuracy: 0.6985
Epoch 7/10
1094/1094 [==============================] - 82s 75ms/step - loss: 0.7001 - accuracy: 0.7532 - val_loss: 1.0620 -

In [36]:
import numpy as np
hin_vocab = target_vectorization.get_vocabulary()
hin_index_lookup = dict(zip(range(len(hin_vocab)), hin_vocab))
max_decoded_sentence_length = 20

def decode_sequence(input_sentence):
    tokenized_input_sentence = source_vectorization([input_sentence])
    decoded_sentence = "[start]"
    for i in range(max_decoded_sentence_length):
        tokenized_target_sentence = target_vectorization(
            [decoded_sentence])[:, :-1]
        predictions = transformer(
            [tokenized_input_sentence, tokenized_target_sentence])
        sampled_token_index = np.argmax(predictions[0, i, :])
        sampled_token = hin_index_lookup[sampled_token_index]
        decoded_sentence += " " + sampled_token
        if sampled_token == "[end]":
            break
    return decoded_sentence

test_eng_texts = [pair[0] for pair in test_pairs]
for _ in range(40):
    input_sentence = random.choice(test_eng_texts)
    print("-")
    print(input_sentence)
    print(decode_sequence(input_sentence))

-
That He did create in pairs, - male and female,
[start] कि और यह है कि हमने उस बस्ती में जो भी जो चीज़ रखी हैं [end]
-
Did you receive the story of Moses,
[start] क्या तुम्हें मूसा की ख़बर पहुँची है [end]
-
How many lines that must be typed before level can change
[start] कितनी [UNK] [UNK] के लिए कैसे आप [UNK] सकते हैं [end]
-
There 's an apple in this boy' s pocket.
[start] इस जंग के लड़का एक औरत की चीज़ है [end]
-
But he did not reply to my question.
[start] लेकिन वह हमारी हस्ताक्षर की बात नहीं कर सकता। [end]
-
O Prophet! Indeed We have sent you as a witness, as a bearer of good news and as a warner
[start] निश्चय ही वह चीज़ हमेशा रहेंगें और वह रहने और ठहरने की अच्छी है [end]
-
“Indeed I fear upon you the punishment of a Great Day. ”
[start] निश्चय ही मुझे तुम्हारे बारे में एक बड़े दिन की यातना का भय है। [end]
-
The other participant canceled the file transfer
[start] दूसरे सहभागी ने फ़ाइल हस्तांतरण रद्द किया [end]
-
Directories cannot be added to video or audio discs
[start] निर्द